theme:
title: "Carnegie Hall Data Lab"
description: "A learning space for Carnegie Hall to experiment with linked open data and semantic technologies."
lang: en-US
site_url: https://carnegiehall.github.io/datalab/
