theme:
title: "Carnegie Hall Data Lab"
description: "A learning space for Carnegie Hall to experiment with linked open data and semantic technologies."
plugins:
  - jekyll-seo-tag
url: "https://github.com/CarnegieHall/datalab"
lang: en-US
